train data: "./data/train/GNSS_raw_train.csv"
features selected: ['Satelite_Code', 'Code_L1', 'Phase_L1', 'Doppler_L1', 'Cnr_L1', 'Cnr_L2']
label name: ["Label"]
data mapper: "./data/datamapper/satelitecode_mapper.json"
train data size: 0.8
train random state: 42
train shuffle: True
model name: "rf"
epochs: 1